Spaces ftw

diff --git a/slay b/slay
--- a/slay
+++ b/slay
@@ -13,11 +13,11 @@ set -e
 ###############################################################################
 
 if [ -e twirl ]; then
-	cd "$(dirname "${BASH_SOURCE[0]}")" \
-		&& . "twirl"
+  cd "$(dirname "${BASH_SOURCE[0]}")" \
+    && . "twirl"
 else
-	printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
-	exit 1
+  printf "\n ⚠️  ./twirl not found  💃🏾 First, you need to twirl on your haters\n"
+  exit 1
 fi
 
 ###############################################################################
@@ -69,47 +69,47 @@ chapter "Installing Dependencies…"
 # NVM
 # -----------------------------------------------------------------------------
 if ! [ -x "$(command -v nvm)" ]; then
-	step "Installing NVM…"
-	curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
-	print_success "NVM installed!"
+  step "Installing NVM…"
+  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.34.0/install.sh | bash
+  print_success "NVM installed!"
   source ~/.bashrc
-	step "Installing latest Node…"
-	nvm install node
-	nvm use node
-	nvm run node --version
-	nodev=$(node -v)
-	print_success "Using Node $nodev!"
+  step "Installing latest Node…"
+  nvm install node
+  nvm use node
+  nvm run node --version
+  nodev=$(node -v)
+  print_success "Using Node $nodev!"
 else
-	print_success_muted "NVM/Node already installed. Skipping."
+  print_success_muted "NVM/Node already installed. Skipping."
 fi
 
 # -----------------------------------------------------------------------------
 # Homebrew
 # -----------------------------------------------------------------------------
 if ! [ -x "$(command -v brew)" ]; then
-	step "Installing Homebrew…"
-	curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
-	export PATH="/usr/local/bin:$PATH"
-	print_success "Homebrew installed!"
+  step "Installing Homebrew…"
+  curl -fsS 'https://raw.githubusercontent.com/Homebrew/install/master/install' | ruby
+  export PATH="/usr/local/bin:$PATH"
+  print_success "Homebrew installed!"
 else
-	print_success_muted "Homebrew already installed. Skipping."
+  print_success_muted "Homebrew already installed. Skipping."
 fi
 
 if brew list | grep -Fq brew-cask; then
-	step "Uninstalling old Homebrew-Cask…"
-	brew uninstall --force brew-cask
-	print_success "Homebrew-Cask uninstalled!"
+  step "Uninstalling old Homebrew-Cask…"
+  brew uninstall --force brew-cask
+  print_success "Homebrew-Cask uninstalled!"
 fi
 
 ###############################################################################
 # INSTALL: brews
 ###############################################################################
 if [ -e $cwd/swag/brews ]; then
-	chapter "Installing Homebrew formulae…"
+  chapter "Installing Homebrew formulae…"
 
-	for brew in $(<$cwd/swag/brews); do
-		install_brews $brew
-	done
+  for brew in $(<$cwd/swag/brews); do
+    install_brews $brew
+  done
 fi
 
 ###############################################################################
@@ -142,12 +142,12 @@ brew update
 # INSTALL: casks
 ###############################################################################
 if [ -e $cwd/swag/casks ]; then
-	chapter "Installing apps via Homebrew…"
+  chapter "Installing apps via Homebrew…"
   brew tap homebrew/cask-drivers # Required for sonos cask
 
-	for cask in $(<$cwd/swag/casks); do
-	    install_application_via_brew $cask
-	done
+  for cask in $(<$cwd/swag/casks); do
+      install_application_via_brew $cask
+  done
 fi
 
 ###############################################################################
@@ -156,23 +156,23 @@ fi
 chapter "Installing apps from App Store…"
 if [ -x mas ]; then
 
-	print_warning "Please install mas-cli first: brew mas. Skipping."
+  print_warning "Please install mas-cli first: brew mas. Skipping."
 
-	else
+  else
 
-	if [ -e $cwd/swag/apps ]; then
-		if mas_setup; then
-			# Workaround for associative array in Bash 3
-			# https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
-			for app in $(<$cwd/swag/apps); do
-				KEY="${app%%::*}"
-				VALUE="${app##*::}"
-				install_application_via_app_store $KEY $VALUE
-			done
-		else
-			print_warning "Please signin to App Store first. Skipping."
-		fi
-	fi
+  if [ -e $cwd/swag/apps ]; then
+    if mas_setup; then
+      # Workaround for associative array in Bash 3
+      # https://stackoverflow.com/questions/6047648/bash-4-associative-arrays-error-declare-a-invalid-option
+      for app in $(<$cwd/swag/apps); do
+        KEY="${app%%::*}"
+        VALUE="${app##*::}"
+        install_application_via_app_store $KEY $VALUE
+      done
+    else
+      print_warning "Please signin to App Store first. Skipping."
+    fi
+  fi
 
 fi
 
@@ -186,13 +186,13 @@ brew cleanup 2> /dev/null
 # INSTALL: npm packages
 ###############################################################################
 if [ -e $cwd/swag/npm ]; then
-	chapter "Installing npm packages…"
+  chapter "Installing npm packages…"
 
-	for pkg in $(<$cwd/swag/npm); do
-		KEY="${pkg%%::*}"
-		VALUE="${pkg##*::}"
-		install_npm_packages $KEY $VALUE
-	done
+  for pkg in $(<$cwd/swag/npm); do
+    KEY="${pkg%%::*}"
+    VALUE="${pkg##*::}"
+    install_npm_packages $KEY $VALUE
+  done
 fi
 
 
